trigger:
- master

pool:
  name: Self-hosted
  demands: Agent.Name -equals ubuntu1

- task: CmdLine@2
  inputs:
    script: |
      echo  '$(System.DefaultWorkingDirectory)'
      dir
      dir subfoldername

