trigger:
- master

pool:
  name: Self-hosted

steps:

- script: |
    java -version
  env:
    JAVA_HOME: $(JAVA_HOME)
    PATH: $(JAVA_HOME)/bin:$(PATH)
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'