trigger:
- master

pool:
  name: Self-hosted
  demands: Agent.Name -equals ubuntu1

steps:

- task: CmdLine@2
      inputs:
        script: |
          echo "Structure of work folder of this pipeline:"
          tree $(Agent.WorkFolder)/1

          echo "Build.ArtifactStagingDirectory:" 
          echo "$(Build.ArtifactStagingDirectory)"

          echo "Build.BinariesDirectory:" 
          echo "$(Build.BinariesDirectory)"

          echo "Build.SourcesDirectory:"
          echo "$(Build.SourcesDirectory)"

